export interface WorkerSeachDataTableFilter {
    fusionAssignmentId: string | null,
    fusionEmployeeId: string | null,
    personId: string | null,
    assignmentId: string | null,
    placementId: number | null,   
    workerName: string | null,
    personType: string | null,
    legalEmployer: string | null,    
    fusionCustomerName: string | null,
    assignmentStatus: string | null,
    employmentStatus: string | null,    
    consultantPointOfContact: string | null,
    workState: string | null,
    reviewedBy: string | null,
    //effectiveEndDate: string,
    // firstName: string | null,
    // lastName: string | null,
    // legacyReportingBu: string | null,
    // supplierName: string | null,
    // serviceLine: string | null,
    // branch: string | null,
    // targetStartDate: string | null,
    // placementReviewStatus: string | null,
    // reviewedDate: null,
    // updatedBy: string | null,
    // updatedDate: null    
}
