export class Assignment {
    asgmtId: string | null | undefined;
    personId: string | null | undefined;
    timeSetupId: string | null | undefined;
    placementStatusId: string | null | undefined;
    hcmAsgmtId: string | null | undefined;
    hcmPersonId: string | null | undefined;
    hcmEmplId: string | null | undefined;
    hcmPersonType: string | null | undefined;
    hcmPersonTypeId: string | null | undefined;
    atsPlacementSource: string | null | undefined;
    atsPlacementStatus: string | null | undefined;
    asgmtTargetEndDate: string | null | undefined;
    asgmtTargetStartDate: string | null | undefined;
    asgmtActualStartDate: string | null | undefined;
    emplStartDate: string | null | undefined;
    emplEndDate: string | null | undefined;
    emplExemptionStatus: string | null | undefined;
    emplExemptionStatusId: string | null | undefined;
    asgmtExemptionStatus: string | null | undefined;
    asgmtExemptionStatusId: string | null | undefined;
    federalGovernmentWorker: string | null | undefined;
    hireReason: string | null | undefined;
    normalWeeklyHoursId: string | null | undefined;
    normalWeeklyHours: string | null | undefined;
    parttimeFulltime: string | null | undefined;
    startDateDelayReason: string | null | undefined;
    asgmtTags: string | null | undefined;
    billCurrency: string | null | undefined;
    billPer: string | null | undefined;
    billPerId: string | null | undefined;
    billingProfile: string | null | undefined;
    clientBillableOt: string | null | undefined;
    clientBillableOtId: string | null | undefined;
    isAsgmtBillable: string | null | undefined;
    isPerDiemApplicable: string | null | undefined;
    isPerDiemBillable: string | null | undefined;
    isPerDiemBillableId: string | null | undefined;
    perDiemBillPayTax: string | null | undefined;
    perDiemEligibility: string | null | undefined;
    perDiemHourLimit: string | null | undefined;
    perDiemPer: string | null | undefined;
    perDiemRate: string | null | undefined;
    perDiemStartDate: string | null | undefined;
    perDiemEndDate: string | null | undefined;
    margin: string | null | undefined;
    markup: string | null | undefined;
    standardBillRate: string | null | undefined;
    overTimeBillRate: string | null | undefined;
    doubleTimeBillRate: string | null | undefined;
    portalFeePercentage: string | null | undefined;
    portalRate: string | null | undefined;
    customerEngagementId: string | null | undefined;
    customerEngagementName: string | null | undefined;
    atsCustomerAccountId: string | null | undefined;
    atsCustomerAccountName: string | null | undefined;
    atsCustomerParentId: string | null | undefined;
    atsCustomerParentName: string | null | undefined;
    fusionCustomerAccountId: string | null | undefined;
    fusionCustomerAccountName: string | null | undefined;
    fusionCustomerParentId: string | null | undefined;
    fusionCustomerParentName: string | null | undefined;
    customerSite: string | null | undefined;
    asgmtEndReason: string | null | undefined;
    asgmtEndComment: string | null | undefined;
    employeeTerminationReason: string | null | undefined;
    endOfPlacementReason: string | null | undefined;
    terminationDate: string | null | undefined;
    intercompanyAssignmentType: string | null | undefined;
    intercompanyTransfer: string | null | undefined;
    transferRate: string | null | undefined;
    deliveryOwner: string | null | undefined;
    project: string | null | undefined;
    projectId: string | null | undefined;
    serviceLine: string | null | undefined;
    serviceLineId: string | null | undefined;
    location: string | null | undefined;
    locationId: string | null | undefined;
    sellingBusinessUnitId: string | null | undefined;
    subLineOfBusiness: string | null | undefined;
    strategicBusinessUnit: string | null | undefined;
    subSegment: string | null | undefined;
    subSubSegment: string | null | undefined;
    isShiftWorker: string | null | undefined;
    shiftNumberShiftType: string | null | undefined;
    shiftEndTime: string | null | undefined;
    shiftStartTime: string | null | undefined;
    shiftTimeZone: string | null | undefined;
    workSchedule: string | null | undefined;
    workScheduleId: string | null | undefined;
    accountNumber: string | null | undefined;
    ceridianPayGroup: string | null | undefined;
    ceridianPayGroupId: string | null | undefined;
    checkLocation: string | null | undefined;
    directDepositDistributionSection: string | null | undefined;
    standardPayRate: string | null | undefined;
    overTimePayRate: string | null | undefined;
    doubleTimePayRate: string | null | undefined;
    epaAuthorization: string | null | undefined;
    methodType: string | null | undefined;
    otRuleOverrideId: string | null | undefined;
    otRuleOverride: string | null | undefined;
    payCurrencyId: string | null | undefined;
    payCurrency: string | null | undefined;
    payCycle: string | null | undefined;
    payCycleName: string | null | undefined;
    payFrequency: string | null | undefined;
    payPer: string | null | undefined;
    payType: string | null | undefined;
    payTypeId: string | null | undefined;
    payWeekendingDay: string | null | undefined;
    payWeekendingDayId: string | null | undefined;
    paystubAddendum: string | null | undefined;
    sendCheckTo: string | null | undefined;
    sendPaystubReportAccessToWorker: string | null | undefined;
    usW2ElectronicConsent: string | null | undefined;
    poDescription: string | null | undefined;
    poEffective: string | null | undefined;
    poEnd: string | null | undefined;
    poNumber: string | null | undefined;
    actualEndDateAsgmt: string | null | undefined;
    additionalData1: string | null | undefined;
    asgmtDescription: string | null | undefined;
    boLocalCode: string | null | undefined;
    boSkillCode: string | null | undefined;
    boStateCode: string | null | undefined;
    brandOffering: string | null | undefined;
    exemptionReason: string | null | undefined;
    exemptionReasonComments: string | null | undefined;
    internalOrg: string | null | undefined;
    lineManager: string | null | undefined;
    multipleAsgmtOrdering: string | null | undefined;
    onboardingTeamReviewRequired: string | null | undefined;
    pieceworkIndicator: string | null | undefined;
    processTeam: string | null | undefined;
    subOrg: string | null | undefined;
    prbuId: string | null | undefined;
    projectBusinessUnit: string | null | undefined;
    projectType: string | null | undefined;
    rateCalculator: string | null | undefined;
    validation: string | null | undefined;
    workerClassification: string | null | undefined;
    workerStatus: string | null | undefined;
    prbuName: string | null | undefined;
    legalEmployer: string | null | undefined;
    legalEmployerId: string | null | undefined;
    workerTypeId: string | null | undefined;
    workerType: string | null | undefined;
    vmsName: string | null | undefined;
    vmsId: string | null | undefined;
    vmsWorkOrderNumber: string | null | undefined;
    vmsWorkerId: string | null | undefined;
    candidateDuplicateCheckIndicator: string | null | undefined;
    candidateId: string | null | undefined;
    placementId: string | null | undefined;
    customerWorker: string | null | undefined;
    hireType: string | null | undefined;
    internalWorker: string | null | undefined;
    legacyEmployeeId: string | null | undefined;
    matchedCandidatedId: string | null | undefined;
    matchedEmployeeId: string | null | undefined;
    onboardingCancellationReason: string | null | undefined;
    onboardingId: string | null | undefined;
    onboardingStatus: string | null | undefined;
    placementSource: string | null | undefined;
    placementStatus: string | null | undefined;
    redeploymentIndicator: string | null | undefined;
    supplierWorker: string | null | undefined;
    caFederalTaxSection: string | null | undefined;
    caProvincialTaxSection: string | null | undefined;
    usFederalTaxSection: string | null | undefined;
    usLocalTaxSection: string | null | undefined;
    usStateTaxSection: string | null | undefined;
    aveDtPayRate: string | null | undefined;
    aveOtPayRate: string | null | undefined;
    aveStPayRate: string | null | undefined;
    atsReferralVendorId: string | null | undefined;
    atsReferralVendorName: string | null | undefined;
    vendorDtBillRate: string | null | undefined;
    vendorCandidate: string | null | undefined;
    vendorNameRecuriter: string | null | undefined;
    vendorOtBillRate: string | null | undefined;
    vendorReferralFee: string | null | undefined;
    vendorStBillRate: string | null | undefined;
    supplierId: string | null | undefined;
    supplierName: string | null | undefined;
    supplierPayGroup: string | null | undefined;
    conversionDate: string | null | undefined;
    conversionFee: string | null | undefined;
    conversionNotes: string | null | undefined;
    conversionSalary: string | null | undefined;
    directHireGuaranteeDuration: string | null | undefined;
    directHireInvoiceSchedule: string | null | undefined;
    directHirePlacementFeeAmount: string | null | undefined;
    directHirePlacementFeePercentage: string | null | undefined;
    directHireVendorAmount: string | null | undefined;
    directHireVendorId: string | null | undefined;
    directHireVendorName: string | null | undefined;
    guaranteeTermsDays: string | null | undefined;
    guaranteeTermsDaysId: string | null | undefined;
    invoiceTermsSpreadIntervals: string | null | undefined;
    invoiceTermsNotes: string | null | undefined;
    billApprover: string | null | undefined;
    clientApproverEmailTimecard: string | null | undefined;
    clientContact: string | null | undefined;
    payApprover: string | null | undefined;
    timesheetApproverClient: string | null | undefined;
    timesheetApproverClientAlternateApprover: string | null | undefined;
    timesheetApproverInternal: string | null | undefined;
    discountedOtBillRate: string | null | undefined;
    specialPayIndicator: string | null | undefined;
    costCentreDivision: string | null | undefined;
    reportingDivision: string | null | undefined;
    alternateWorkSchedule: string | null | undefined;
    consultantPointOfContact: string | null | undefined;
    consultantPointOfContactId: string | null | undefined;
    onBoardingSpecialist: string | null | undefined;
    onBoardingSpecialistId: string | null | undefined;
    timeManagementSpecialist: string | null | undefined;
    timeManagementSpecialistId: string | null | undefined;
    csfTemplateId: string | null | undefined;
    billingCodeExpenses: string | null | undefined;
    billingCodePiecework: string | null | undefined;
    branchName: string | null | undefined;
    hcmAsgmtStatus: string | null | undefined;
    hcmEmplStatus: string | null | undefined;
    parttimeFullTimeId: string | null | undefined;
    startDateDelayReasonId: string | null | undefined;
    billCurrencyId: string | null | undefined;
    sellingBusinessUnitName: string | null | undefined;
    payCycleId: string | null | undefined;
    payFrequencyId: string | null | undefined;
    directDepositDistributionSectionCollection: string | null | undefined;
    createdBy: string | null | undefined;
    createdDate: string | null | undefined;
    modifiedBy: string | null | undefined;
    modifiedDate: string | null | undefined;
    legacyReportingBusinessUnit: string | null | undefined;
    isRehireEligibleId: string | null | undefined;
    isRehireEligible: string | null | undefined;
    attestationId:string | null | undefined;
    attestationName: string | null | undefined;
    vacationCode:string | null | undefined;
    vacationId: string | null | undefined;
    shadowStrategicBusinessUnit: string | null | undefined;
    nationalId:string | null | undefined;
    national: string | null | undefined;
    atsJobId: string | null | undefined;


    constructor(data: Assignment) {
        Object.assign(this, data);
    }
}

export class AssignmentAudit {
    hcmPersonType: string = 'Person Type (HCM Identifiers)';
    asgmtTargetEndDate: string = 'Target End Date - Assignment';
    asgmtTargetStartDate: string = 'Target Start Date - Assignment';
    asgmtActualStartDate: string = 'Actual Start Date - Assignment';
    emplExemptionStatus: string = 'Employment Exemption Status';
    asgmtExemptionStatus: string = 'Assignment Exemption Status';
    normalWeeklyHours: string = 'Normal Weekly Hours';
    parttimeFulltime: string = 'Part-Time or Full- Time';
    startDateDelayReason: string = 'Start Date Delay Reason';
    billCurrency: string = 'Bill Currency';
    billPer: string = 'Bill Per';
    clientBillableOt: string = 'Client Billable OT';
    isPerDiemBillable: string = 'Is Per Diem Billable';
    perDiemRate: string = 'Per Diem Rate';
    perDiemStartDate: string = 'Per Diem Start Date';
    perDiemEndDate: string = 'Per Diem End Date';
    standardBillRate: string = 'Standard Bill Rate';
    overTimeBillRate: string = 'Over Time Bill Rate';
    doubleTimeBillRate: string = 'Double Time Bill Rate';
    portalFeePercentage: string = 'Portal Fee Percentage';
    atsCustomerAccountId: string = 'ATS Customer ID(Account)';
    atsCustomerAccountName: string = 'ATS Customer Name (Account)';
    atsCustomerParentId: string = 'ATS Customer ID(Parent)';
    atsCustomerParentName: string = 'ATS Customer Name (Parent)';
    fusionCustomerAccountId: string = 'Fusion Customer ID (Account)';
    fusionCustomerAccountName: string = 'Fusion Customer Name (Account)';
    fusionCustomerParentId: string = 'Fusion Customer ID (Parent)';
    fusionCustomerParentName: string = 'Fusion Customer Name (Parent)';
    customerSite: string = 'Customer Site (Billing Location)';
    deliveryOwner: string = 'Delivery Owner';
    project: string = 'Project';
    serviceLine: string = 'Line of Business';
    location: string = 'Finance Location';
    strategicBusinessUnit: string = 'Strategic Business Unit';
    subSegment: string = 'Sub-Segment (Sub Vertical)';
    workSchedule: string = 'Alternative Work Schedule';
    ceridianPayGroup: string = 'Pay Group';
    standardPayRate: string = 'Standard Pay Rate';
    overTimePayRate: string = 'Over Time Pay Rate';
    doubleTimePayRate: string = 'Double Time Pay Rate';
    otRuleOverride: string = 'OT Rule Override';
    payCurrency: string = 'Pay Currency';
    payCycle: string = 'Pay Cycle';
    payFrequency: string = 'Pay Frequency';
    payType: string = 'Pay Type';
    payWeekendingDay: string = 'Pay Weekending Day';
    poDescription: string = 'PO Description';
    poEffective: string = 'PO Effective Date';
    poEnd: string = 'PO End Date';
    poNumber: string = 'PO Number';
    projectBusinessUnit: string = 'Project Business Unit';
    projectType: string = 'Project Type';
    prbuName: string = 'Legacy Business Unit';
    legalEmployer: string = 'Legal Entity';
    workerType: string = 'Worker Type';
    vmsName: string = 'VMS Name';
    vmsWorkOrderNumber: string = 'VMS Work Order Number';
    vmsWorkerId: string = 'VMS WorkerID';
    candidateId: string = 'Candidate ID';
    placementId: string = 'Placement ID';
    hireType: string = 'Hire Type';
    matchedEmployeeId: string = 'Matched Employee ID';
    onboardingCancellationReason: string = 'Onboarding Cancellation Reason';
    onboardingId: string = 'Onboarding ID';
    onboardingStatus: string = 'Onboarding Status';
    placementSource: string = 'Placement Source';
    placementStatus: string = 'Placement Status';
    aveDtPayRate: string = 'AVE DT Pay Rate $';
    aveOtPayRate: string = 'AVE OT Pay Rate $';
    aveStPayRate: string = 'AVE ST Pay Rate $';
    supplierId: string = 'ATS Supplier ID';
    supplierName: string = 'ATS Supplier Name';
    timesheetApproverClient: string = 'TimeSheet Approver - Client';
    timesheetApproverClientAlternateApprover: string = 'TimeSheet Approver - Client Alternate Approver';
    discountedOtBillRate: string = 'Discounted OT Bill Rate';
    consultantPointOfContact: string = 'Consultant Point Of Contact';
    onBoardingSpecialist: string = 'On-Boarding Specialist';
    timeManagementSpecialist: string = 'Time Management Specialist';
    shadowStrategicBusinessUnit:string = 'Shadow Strategic Business Unit';
    attestationName: string = 'Attestation Flag';
    national :string =  'National Id Type' ;
    vacationCode:string= 'Vacation'

    constructor() {}
}
