export class AssignmentTeamAddr {
    asgmtId: string | null | undefined;
    clientServiceManager: string | null | undefined;
    clientServiceManagerId:string | null | undefined;
    geographyBranches: string | null | undefined;
    recruiter: string | null | undefined;
    recruiterId:string | null | undefined;
    recruiterPercentage: string | null | undefined;
    recruiterPercentageId:string | null | undefined;
    recruiterSecondary: string | null | undefined;
    recruiterSecondaryId:string | null | undefined;
    recruiterSecondaryPercentage: string | null | undefined;
    recruiterSecondaryPercentageId:string | null | undefined;
    recruiterTertiary: string | null | undefined;
    recruiterTertiaryPercentage: string | null | undefined;
    recruiterOverride: string | null | undefined;
    recruiterOverrideId:string | null | undefined;
    recruiterTeam: string | null | undefined;
    recruiterTeamId:string | null | undefined;
    nonCommissionableRecruiter: string | null | undefined;
    nonCommissionableRecruiterId: string | null | undefined;
    revenueDiscount: string | null | undefined;
    salesPerson: string | null | undefined;
    salesPersonId:string | null | undefined;
    salesPersonPercentage: string | null | undefined;
    salesPersonPercentageId:string | null | undefined;
    salesPersonSecondary: string | null | undefined;
    salesPersonSecondaryId: string | null | undefined;
    salesPersonSecondaryPercentage: string | null | undefined;
    salesPersonSecondaryPercentageId: string | null | undefined;
    salesPersonTertiary: string | null | undefined;
    salesPersonTertiaryPercentage: string | null | undefined;
    salesTeam: string | null | undefined;
    salesTeamId: string | null | undefined;
    salesTeamOverride: string | null | undefined;
    salesTeamOverrideId: string | null | undefined;
    salesPersonOverride:string | null | undefined;
    salesPersonOverrideId: string | null | undefined;
    nonCommissionableSalesPerson: string | null | undefined;
    nonCommissionableSalesPersonId: string | null | undefined;
    tenureDiscountCustomer: string | null | undefined;
    lcaAmount: string | null | undefined;
    workAddress: string | null | undefined;
    county: string | null | undefined;
    state: string | null | undefined;
    stateId: string | null | undefined;
    streetAddressLine1: string | null | undefined;
    streetAddressLine2: string | null | undefined;
    // streetAddressLine3: string | null | undefined;
    workerSiteType: string | null | undefined;
    workingRemoteId: string | null | undefined;
    workingRemote: string | null | undefined;
    coeArea: string | null | undefined;
    coeDirector: string | null | undefined;
    coeEmployee: string | null | undefined;
    coeRole: string | null | undefined;
    primaryCoeAre: string | null | undefined;
    secondaryCoeArea: string | null | undefined;
    solutionOversight: string | null | undefined;
    burdenCode: string | null | undefined;
    businessTitle: string | null | undefined;
    hoursPerDay: string | null | undefined;
    jobClass: string | null | undefined;
    jobDescription: string | null | undefined;
    jobDuration: string | null | undefined;
    jobTitle: string | null | undefined;
    jobType: string | null | undefined;
    replacement: string | null | undefined;
    workersCompCode: string | null | undefined;
    city: string | null | undefined;
    contactAddressLine1: string | null | undefined;
    contactAddressLine2: string | null | undefined;
    contactEmail: string | null | undefined;
    contactName: string | null | undefined;
    contactType: string | null | undefined;
    country: string | null | undefined;
    countryId: string | null | undefined;
    stateProvince: string | null | undefined;
    zip: string | null | undefined;
    referallVendorId: string | null | undefined;
    referralEndDate: string | null | undefined;
    referralGetPaidTermsDays: string | null | undefined;
    referralRatePercentageValue: string | null | undefined;
    referralRateType: string | null | undefined;
    referralStartDate: string | null | undefined;
    referralVendorName: string | null | undefined;
    referralVendorType: string | null | undefined;
    supplierId: string | null | undefined;
    supplierName: string | null | undefined;
    supplierPayGroup: string | null | undefined;
    contactCity: string | null | undefined;
    contactCountry: string | null | undefined;
    contactCountryId: string | null | undefined;
    contactStateProvince: string | null | undefined;
    contactStateProvinceId: string | null | undefined;
    contactZip: string | null | undefined;
    voltJobTitle: string | null | undefined;
    industry: string | null | undefined;
    createdBy: string | null | undefined;
    createdDate: string | null | undefined;
    modifiedBy: string | null | undefined;
    modifiedDate: string | null | undefined;
    internalJobCode: string | null | undefined;
    internalJobTittle: string | null | undefined;
    fusionSupplierName: string | null | undefined;
    fusionSupplierId: string | null | undefined;
    holidayPlanTypeName: string | null | undefined;
    holidayPlanTypeId: string | null | undefined;
    internalJobCodeId: string | null | undefined;
    internalJobCodeName: string | null | undefined;
    workaddrIsGoogleValidated: string | null | undefined;
    workaddrGoogleOverrideInd: string | null | undefined;
    workaddrGoogleOverrideReason: string | null | undefined;

    constructor(data: AssignmentTeamAddr) {
        Object.assign(this, data);
    }
}

export class AssignmentTeamAddrAudit {
    clientServiceManager: string = 'Client Service Manager';
    recruiter: string = 'Recruiter';
    recruiterPercentage: string = 'Recruiter Percentage';
    recruiterSecondary: string = 'Recruiter Secondary';
    recruiterSecondaryPercentage: string = 'Recruiter Secondary Percentage';
    recruiterTeam: string = 'Recruiter Team';
    salesPerson: string = 'Sales Person';
    salesPersonPercentage: string = 'Sales Person-Percentage';
    salesPersonSecondary: string = 'Sales Person-Secondary';
    salesPersonSecondaryPercentage: string = 'Sales Person-Secondary-Percentage';
    salesTeam: string = 'Sales Team';
    salesTeamOverride: string = 'Sales Team Override';
    county: string = 'County (Worker Address)';
    state: string = 'State (Worker Address)';
    streetAddressLine1: string = 'Street Address Line 1 (Worker Address)';
    streetAddressLine2: string = 'Street Address Line 2 (Worker Address)';
    // streetAddressLine3: string = 'Street Address Line 3 (Worker Address)';
    workingRemote: string = 'Working Remote (Worker Address)';
    jobTitle: string = 'Job Title';
    city: string = 'City (Worker Address)';
    contactAddressLine1: string = 'Contact Address Line 1';
    contactAddressLine2: string = 'Contact Address Line 2';
    contactEmail: string = 'Client Contact Email';
    contactName: string = 'Client Contact Name';
    contactType: string = 'Client Contact Type';
    country: string = 'Country (Worker Address)';
    zip: string = 'Zip (Worker Address)';
    contactCity: string = 'Client Contact City';
    contactCountry: string = 'Client Contact Country';
    contactStateProvince: string = 'Client Contact State/Province';
    contactZip: string = 'Client Contact Zip';
    internalJobCode: string = 'Internal Job Code';
    internalJobTittle: string = 'Internal Job Title';
    fusionSupplierName: string = 'Fusion Supplier ID';
    fusionSupplierId: string = 'Fusion Supplier Name';
    recruiterOverride:string = 'Recuiter Override';
    nonCommissionableRecruiter:string = ' Non Commissionable Recruiter';
    salesPersonOverride:string = 'Sales Person Override';
    nonCommissionableSalesPerson:string = 'Non Commissionable Sales Person';
    holidayPlanTypeName: string= 'Holiday Plan Type';
    workaddrIsGoogleValidated: string  = 'Google Validated';
    workaddrGoogleOverrideInd: string  = 'Override Reason';
    workaddrGoogleOverrideReason: string = 'Google Override Indicator';
   

    constructor() {
    }
}
