export class TimeSetupRates {
    timeElementId: string | null | undefined;
    payNigtDiffrlStd: string | null | undefined;
    payNigtDiffrlOt: string | null | undefined;
    payNigtDiffrlDt: string | null | undefined;
    payNigtDiffrlEffDateFrom: string | null | undefined;
    payNigtDiffrlEffDateEnd: string | null | undefined;
    payMealPremiumStd: string | null | undefined;
    payMealPremiumOt: string | null | undefined;
    payMealPremiumDt: string | null | undefined;
    payMealPremiumEffDateFrom: string | null | undefined;
    payMealPremiumEffDateEnd: string | null | undefined;
    payOnCallPagerStd: string | null | undefined;
    payOnCallPagerOt: string | null | undefined;
    payOnCallPagerDt: string | null | undefined;
    payOnCallPagerEffDateFrom: string | null | undefined;
    payOnCallPagerEffDateEnd: string | null | undefined;
    payHealthWelfareStd: string | null | undefined;
    payHealthWelfareOt: string | null | undefined;
    payHealthWelfareDt: string | null | undefined;
    payHealthWelfEffDateFrom: string | null | undefined;
    payHealthWelfEffDateEnd: string | null | undefined;
    payVacBillableStd: string | null | undefined;
    payVacBillableOt: string | null | undefined;
    payVacBillableDt: string | null | undefined;
    payVacBillableEffDateFrom: string | null | undefined;
    payVacBillableEffDateEnd: string | null | undefined;
    payMileageStd: string | null | undefined;
    payMileageOt: string | null | undefined;
    payMileageDt: string | null | undefined;
    payMileageEffDateFrom: string | null | undefined;
    payMileageEffDateEnd: string | null | undefined;
    paySickStd: string | null | undefined;
    paySickOt: string | null | undefined;
    paySickDt: string | null | undefined;
    paySickEffDateFrom: string | null | undefined;
    paySickEffDateEnd: string | null | undefined;
    payHolidayStd: string | null | undefined;
    payHolidayOt: string | null | undefined;
    payHolidayDt: string | null | undefined;
    payHolidayEffDateFrom: string | null | undefined;
    payHolidayEffDateEnd: string | null | undefined;
    blNigtDiffrlStd: string | null | undefined;
    blNigtDiffrlOt: string | null | undefined;
    blNigtDifferentialDt: string | null | undefined;
    blNigtDiffrlEffDateFrom: string | null | undefined;
    blNigtDiffrlEffDateEnd: string | null | undefined;
    blMealPrmStd: string | null | undefined;
    blMealPrmOt: string | null | undefined;
    blMealPrmDt: string | null | undefined;
    blMealPrmEffDateFrom: string | null | undefined;
    blMealPrmEffDateEnd: string | null | undefined;
    blOnCallPagerStd: string | null | undefined;
    blOnCallPagerOt: string | null | undefined;
    blOnCallPagerDt: string | null | undefined;
    blOnCallPagerEffDateFrom: string | null | undefined;
    blOnCallPagerEffDateEnd: string | null | undefined;
    blHealthWelfareStd: string | null | undefined;
    blHealthWelfareOt: string | null | undefined;
    blHealthWelfareDt: string | null | undefined;
    blHealthWelfareEffDateFrom: string | null | undefined;
    blHealthWelfareEffDateEffDateEnd: string | null | undefined;
    blVacBlableStd: string | null | undefined;
    blVacBillableOt: string | null | undefined;
    blVacBillableDt: string | null | undefined;
    blVacBillableEffDateFrom: string | null | undefined;
    blVacBillableEffDateEnd: string | null | undefined;
    blMileageStd: string | null | undefined;
    blMileageOt: string | null | undefined;
    blMileageDt: string | null | undefined;
    blMileageEffDateFrom: string | null | undefined;
    blMileageEffDateEnd: string | null | undefined;
    blSickStd: string | null | undefined;
    blSickOt: string | null | undefined;
    blSickDt: string | null | undefined;
    blSickEffDateFrom: string | null | undefined;
    blSickEffDateEnd: string | null | undefined;
    blHolidayStd: string | null | undefined;
    blHolidayOt: string | null | undefined;
    blHolidayDt: string | null | undefined;
    blHolidayEffDateFrom: string | null | undefined;
    blHolidayEffDateEnd: string | null | undefined;
    paySickNonBillStd: string | null | undefined;
    paySickNonBillOt: string | null | undefined;
    paySickNonBillDt: string | null | undefined;
    paySickNonBillEffDateFrom: string | null | undefined;
    paySickNonBillEffDateEnd: string | null | undefined;

    constructor(data: TimeSetupRates) {
        Object.assign(this, data);
    }
}

export class TimeSetupRatesAudit {
    timeElementId: string = '';
    payNigtDiffrlStd: string = 'Night Differential Standard (Pay)';
    payNigtDiffrlOt: string = 'Night Differential Overtime (Pay)';
    payNigtDiffrlDt: string = 'Night Differential Double Time (Pay)';
    payNigtDiffrlEffDateFrom: string = 'Night Differential Effective Start Date (Pay)';
    payNigtDiffrlEffDateEnd: string = 'Night Differential Effective End Date (Pay)';
    payMealPremiumStd: string = 'Meal Premium Standard (Pay)';
    payMealPremiumOt: string = 'Meal Premium Overtime (Pay)';
    payMealPremiumDt: string = 'Meal Premium Double Time (Pay)';
    payMealPremiumEffDateFrom: string = 'Meal Premium Effective Start Date (Pay)';
    payMealPremiumEffDateEnd: string = 'Meal Premium Effective End Date (Pay)';
    payOnCallPagerStd: string = 'On Call/Pager Standard (Pay)';
    payOnCallPagerOt: string = 'On Call/Pager Overtime (Pay)';
    payOnCallPagerDt: string = 'On Call/Pager Double Time (Pay)';
    payOnCallPagerEffDateFrom: string = 'On Call/Pager Effective Start Date (Pay)';
    payOnCallPagerEffDateEnd: string = 'On Call/Pager Effective End Date (Pay)';
    payHealthWelfareStd: string = 'Health & Welfare Standard (Pay)';
    payHealthWelfareOt: string = 'Health & Welfare Overtime (Pay)';
    payHealthWelfareDt: string = 'Health & Welfare Double Time (Pay)';
    payHealthWelfEffDateFrom: string = 'Health & Welfare Effective Start Date (Pay)';
    payHealthWelfEffDateEnd: string = 'Health & Welfare Effective End Date (Pay)';
    payVacBillableStd: string = 'Vacation Billable Standard (Pay)';
    payVacBillableOt: string = 'Vacation Billable Overtime (Pay)';
    payVacBillableDt: string = 'Vacation Billable Double Time (Pay)';
    payVacBillableEffDateFrom: string = 'Vacation Billable Effective Start Date (Pay)';
    payVacBillableEffDateEnd: string = 'Vacation Billable Effective End Date (Pay)';
    payMileageStd: string = 'Mileage Pay Standard (Pay)';
    payMileageOt: string = 'Mileage Pay Overtime (Pay)';
    payMileageDt: string = 'Mileage Pay Double Time (Pay)';
    payMileageEffDateFrom: string = 'Mileage Pay Effective Start Date (Pay)';
    payMileageEffDateEnd: string = 'Mileage Pay Effective End Date (Pay)';
    paySickStd: string = 'Sick Pay Billable Standard (Pay)';
    paySickOt: string = 'Sick Pay Billable Overtime (Pay)';
    paySickDt: string = 'Sick Pay Billable Double Time (Pay)';
    paySickEffDateFrom: string = 'Sick Pay Billable Effective Start Date (Pay)';
    paySickEffDateEnd: string = 'Sick Pay Billable Effective End Date (Pay)';
    paySickNonBillStd: string = 'Sick Pay Non-Billable Standard (Pay)';
    paySickNonBillOt: string = 'Sick Pay Non-Billable Overtime (Pay)';
    paySickNonBillDt: string = 'Sick Pay Non-Billable Double Time (Pay)';
    paySickNonBillEffDateFrom: string = 'Sick Pay Non-Billable Effective Start Date (Pay)';
    paySickNonBillEffDateEnd: string = 'Sick Pay Non-Billable Effective End Date (Pay)';
    payHolidayStd: string = 'Holiday Standard (Pay)';
    payHolidayOt: string = 'Holiday Overtime (Pay)';
    payHolidayDt: string = 'Holiday Double Time (Pay)';
    payHolidayEffDateFrom: string = 'Holiday Effective Start Date (Pay)';
    payHolidayEffDateEnd: string = 'Holiday Effective End Date (Pay)';
    blNigtDiffrlStd: string = 'Night Differential Standard (Bill)';
    blNigtDiffrlOt: string = 'Night Differential Overtime (Bill)';
    blNigtDifferentialDt: string = 'Night Differential Double Time (Bill)';
    blNigtDiffrlEffDateFrom: string = 'Night Differential Effective Start Date (Bill)';
    blNigtDiffrlEffDateEnd: string = 'Night Differential Effective End Date (Bill)';
    blMealPrmStd: string = 'Meal Premium Standard (Bill)';
    blMealPrmOt: string = 'Meal Premium Overtime (Bill)';
    blMealPrmDt: string = 'Meal Premium Double Time (Bill)';
    blMealPrmEffDateFrom: string = 'Meal Premium Effective Start Date (Bill)';
    blMealPrmEffDateEnd: string = 'Meal Premium Effective End Date (Bill)';
    blOnCallPagerStd: string = 'On Call/Pager Standard (Bill)';
    blOnCallPagerOt: string = 'On Call/Pager Overtime (Bill)';
    blOnCallPagerDt: string = 'On Call/Pager Double Time (Bill)';
    blOnCallPagerEffDateFrom: string = 'On Call/Pager Effective Start Date (Bill)';
    blOnCallPagerEffDateEnd: string = 'On Call/Pager Effective End Date (Bill)';
    blHealthWelfareStd: string = 'Health & Welfare Standard (Bill)';
    blHealthWelfareOt: string = 'Health & Welfare Overtime (Bill)';
    blHealthWelfareDt: string = 'Health & Welfare Double Time (Bill)';
    blHealthWelfareEffDateFrom: string = 'Health & Welfare Effective Start Date (Bill)';
    blHealthWelfareEffDateEffDateEnd: string = 'Health & Welfare Effective End Date (Bill)';
    blVacBlableStd: string = 'Vacation Billable Standard (Bill)';
    blVacBillableOt: string = 'Vacation Billable Overtime (Bill)';
    blVacBillableDt: string = 'Vacation Billable Double Time (Bill)';
    blVacBillableEffDateFrom: string = 'Vacation Billable Effective Start Date (Bill)';
    blVacBillableEffDateEnd: string = 'Vacation Billable Effective End Date (Bill)';
    blMileageStd: string = 'Mileage Standard (Bill)';
    blMileageOt: string = 'Mileage Overtime (Bill)';
    blMileageDt: string = 'Mileage Double Time (Bill)';
    blMileageEffDateFrom: string = 'Mileage Effective Start Date (Bill)';
    blMileageEffDateEnd: string = 'Mileage Effective End Date (Bill)';
    blSickStd: string = 'Sick Pay Standard (Bill)';
    blSickOt: string = 'Sick Pay Overtime (Bill)';
    blSickDt: string = 'Sick Pay Double Time (Bill)';
    blSickEffDateFrom: string = 'Sick Pay Effective Start Date (Bill)';
    blSickEffDateEnd: string = 'Sick Pay Effective End Date (Bill)';
    blHolidayStd: string = 'Holiday Pay Standard (Bill)';
    blHolidayOt: string = 'Holiday Pay Overtime (Bill)';
    blHolidayDt: string = 'Holiday Pay Double Time (Bill)';
    blHolidayEffDateFrom: string = 'Holiday Pay Effective Start Date (Bill)';
    blHolidayEffDateEnd: string = 'Holiday Pay Effective End Date (Bill)';

    constructor() {}
}
