export const LocalStorageVariables = {
    workerSearchtimer: 'workerSearchtimer',
    currentUser: 'currentUser',
    authDetails: 'authDetails',
    isLogin: 'isLogin',
    timer: 'timer',
    token: 'token',
    ProxyUrls: 'ProxyUrls',
    EmploymentDashboard: 'EmploymentDashboard',
    UserInformationData: 'userInformationData',
    MsalConfigData: 'msal-configData',
    MsalConfigVoltData: 'msal-volt-configData',
    ApiAccessToken: 'apiAccessToken',
    SSOSource: 'SSOSource',
    workerSearchColumns: 'WorkerSearchColumns',
    placementRepositoryColumns: 'PlacementRepositoryColumns',
    placementRepoSelectedColList: 'placementRepoSelectedColList',
    workerSearchSelectedColList: 'workerSearchSelectedColList',
    placementRepositoryAdvancedSearchFilter: 'placementRepositoryAdvancedSearchFilter',
    workerSearchAdvancedSearchFilter: 'workerSearchAdvancedSearchFilter',
    appUserRole: 'appUserRole',
    userPermission:'userPermissions',
    sourceTypeId :'sourceTypeId'
};
